site_name: Carl-bot Documentation
theme: 
  name: 'material'
  logo:
    'images/googleturtle.svg'
  favicon:
    'images/favicon.ico'
  feature:
    tabs: true
  palette:
    primary: 'Blue Grey'
    accent: 'Cyan'
  font:
    text: 'Roboto'
    code: 'Fira Mono'
  
repo_name: 'carlbot-docs'
repo_url: 'https://github.com/CarlGroth/carlbot-docs'

extra:
  social:
    - type: 'globe'
      link: 'https://carl.gg'
    - type: 'github-alt'
      link: 'https://github.com/CarlGroth'
    - type: 'twitter'
      link: 'https://twitter.com/Carlgrrr'

markdown_extensions:
  - admonition

google_analytics:
  - 'UA-126357432-1'
  - 'auto'

copyright: 'Copyright &copy; 2018 - 2019 Carl (admin@carl.gg)'
